"""
comms/wifi_relay.py — Airborne WiFi Communications Relay

Positions the drone at relay altitude, creates a WiFi hotspot using
hostapd, and acts as a mesh bridge between isolated ground units
when all infrastructure is down.

Requires:
  - Alfa AWUS036ACM adapter (hostapd AP mode support)
  - Root/sudo for hostapd and dnsmasq
  - wlan1 (or configured WIFI_INTERFACE) available and driver loaded
"""

import logging
import os
import subprocess
import threading
import time
from typing import Optional

import config
from flight.drone_control import DroneController

logger = logging.getLogger("AURA.wifi_relay")


HOSTAPD_CONF_TEMPLATE = """
# Generated by AURA Drone — wifi_relay.py
interface={interface}
driver=nl80211
ssid={ssid}
hw_mode=g
channel={channel}
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase={password}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
country_code={country}
"""

DNSMASQ_CONF_TEMPLATE = """
# Generated by AURA Drone — wifi_relay.py
interface={interface}
dhcp-range=192.168.88.10,192.168.88.50,255.255.255.0,24h
dhcp-option=3,192.168.88.1
dhcp-option=6,8.8.8.8
"""


class WiFiRelay:
    """
    Deploys the drone as an airborne WiFi access point / relay node.

    Workflow:
    1. Ascend to RELAY_ALTITUDE_M
    2. Write hostapd + dnsmasq config files
    3. Assign static IP to WiFi interface
    4. Start hostapd (AP mode) and dnsmasq (DHCP)
    5. Monitor connected clients and battery
    6. On low battery: gracefully shutdown AP, land

    All config files are written to /tmp — no permanent filesystem changes.
    """

    def __init__(self, drone: DroneController, alerts=None) -> None:
        self.drone = drone
        self.alerts = alerts
        self._running = False
        self._hostapd_proc: Optional[subprocess.Popen] = None
        self._dnsmasq_proc: Optional[subprocess.Popen] = None
        self._monitor_thread: Optional[threading.Thread] = None

    def deploy(self, altitude_m: float = None) -> bool:
        """
        Ascend to relay altitude and activate WiFi AP.

        Args:
            altitude_m: Override relay altitude (defaults to config.RELAY_ALTITUDE_M)

        Returns:
            True if AP successfully started
        """
        altitude = altitude_m or config.RELAY_ALTITUDE_M
        logger.info(f"Deploying WiFi relay at {altitude}m")

        # Ascend to relay altitude
        telemetry = self.drone.get_telemetry()
        if telemetry.get("altitude_m", 0) < 2.0:
            if not self.drone.takeoff(altitude_m=altitude):
                logger.error("Takeoff failed for relay deployment")
                return False

        # Fly to relay altitude if not already there
        current_alt = self.drone.get_telemetry().get("altitude_m", 0)
        if abs(current_alt - altitude) > 5:
            telemetry = self.drone.get_telemetry()
            self.drone.fly_to(
                lat=telemetry.get("latitude", 0),
                lon=telemetry.get("longitude", 0),
                alt=altitude,
            )

        self.drone.hover()

        # Start AP
        if not self._start_ap():
            logger.error("Failed to start WiFi AP")
            return False

        self._running = True
        self._start_monitor()
        logger.info(f"WiFi relay ACTIVE — SSID: {config.WIFI_SSID}")
        if self.alerts:
            self.alerts.add_alert(
                "RELAY ACTIVE",
                f"WiFi relay broadcasting: {config.WIFI_SSID} @ {altitude}m",
                "info",
            )
        return True

    def teardown(self) -> None:
        """Stop AP and land drone."""
        logger.info("Tearing down WiFi relay")
        self._running = False
        self._stop_ap()
        if self.alerts:
            self.alerts.add_alert("RELAY STOPPED", "WiFi relay shut down", "info")

    # ──────────────────────────────────────────
    # AP Management
    # ──────────────────────────────────────────

    def _start_ap(self) -> bool:
        """Write configs and start hostapd + dnsmasq."""
        interface = config.WIFI_INTERFACE

        # Write hostapd config
        hostapd_conf = HOSTAPD_CONF_TEMPLATE.format(
            interface=interface,
            ssid=config.WIFI_SSID,
            channel=config.WIFI_CHANNEL,
            password=config.WIFI_PASSWORD,
            country=config.WIFI_COUNTRY_CODE,
        )
        hostapd_path = "/tmp/aura_hostapd.conf"
        with open(hostapd_path, "w") as f:
            f.write(hostapd_conf)

        # Write dnsmasq config
        dnsmasq_conf = DNSMASQ_CONF_TEMPLATE.format(interface=interface)
        dnsmasq_path = "/tmp/aura_dnsmasq.conf"
        with open(dnsmasq_path, "w") as f:
            f.write(dnsmasq_conf)

        try:
            # Assign static IP to interface
            subprocess.run(
                ["ip", "addr", "add", "192.168.88.1/24", "dev", interface],
                check=False, capture_output=True
            )
            subprocess.run(
                ["ip", "link", "set", interface, "up"],
                check=True, capture_output=True
            )

            # Start hostapd
            self._hostapd_proc = subprocess.Popen(
                ["hostapd", hostapd_path],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE
            )

            # Give hostapd time to start
            time.sleep(2)

            if self._hostapd_proc.poll() is not None:
                stderr = self._hostapd_proc.stderr.read().decode()
                logger.error(f"hostapd failed to start: {stderr}")
                return False

            # Start dnsmasq for DHCP
            self._dnsmasq_proc = subprocess.Popen(
                ["dnsmasq", "-C", dnsmasq_path, "--no-daemon"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE
            )

            logger.info("hostapd and dnsmasq started")
            return True

        except FileNotFoundError as e:
            logger.error(
                f"hostapd/dnsmasq not found: {e}. "
                "Install with: sudo apt install hostapd dnsmasq"
            )
            return False
        except Exception as e:
            logger.error(f"AP start error: {e}")
            return False

    def _stop_ap(self) -> None:
        """Terminate hostapd and dnsmasq processes."""
        for proc in [self._hostapd_proc, self._dnsmasq_proc]:
            if proc and proc.poll() is None:
                try:
                    proc.terminate()
                    proc.wait(timeout=5)
                except Exception:
                    proc.kill()

        # Clean up IP assignment
        try:
            subprocess.run(
                ["ip", "addr", "del", "192.168.88.1/24", "dev", config.WIFI_INTERFACE],
                check=False, capture_output=True
            )
        except Exception:
            pass

        logger.info("AP stopped")

    # ──────────────────────────────────────────
    # Monitoring
    # ──────────────────────────────────────────

    def _start_monitor(self) -> None:
        """Start background thread to monitor AP health and battery."""
        self._monitor_thread = threading.Thread(
            target=self._monitor_loop, name="RelayMonitor", daemon=True
        )
        self._monitor_thread.start()

    def _monitor_loop(self) -> None:
        """Periodically check battery and connected client count."""
        while self._running:
            time.sleep(30)

            # Battery check
            telemetry = self.drone.get_telemetry()
            bat = telemetry.get("battery_percent", 100)

            if bat <= config.BATTERY_WARN_PERCENT:
                logger.warning(f"Relay battery low ({bat}%) — shutting down relay")
                self.teardown()
                self.drone.land()
                return

            # Count connected clients
            client_count = self._count_clients()
            logger.info(f"Relay status: {client_count} client(s) connected | Battery: {bat}%")

            # Re-alert if clients connected
            if client_count > 0 and self.alerts:
                self.alerts.add_alert(
                    "RELAY STATUS",
                    f"{client_count} device(s) connected to relay | Bat: {bat}%",
                    "info",
                )

    def _count_clients(self) -> int:
        """Count DHCP leases as a proxy for connected client count."""
        try:
            leases_file = "/tmp/dnsmasq.leases"
            if os.path.exists(leases_file):
                with open(leases_file) as f:
                    return sum(1 for line in f if line.strip())
        except Exception:
            pass
        return 0

    def get_connected_clients(self) -> list[dict]:
        """Return list of connected client info from DHCP leases."""
        clients = []
        try:
            result = subprocess.run(
                ["iw", config.WIFI_INTERFACE, "station", "dump"],
                capture_output=True, text=True
            )
            # Parse station dump for connected STAs
            for line in result.stdout.splitlines():
                if "Station" in line:
                    mac = line.split()[1]
                    clients.append({"mac": mac})
        except Exception:
            pass
        return clients
